/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import NextLink from 'next/link';
import React, { useCallback, useEffect, useState } from 'react';
import { AuthGuard } from '@components/authentication/auth-guard';
import { MainLayout } from '@layouts/main-layout';
import { Page } from '../types/page';
import { Box, Button, Container, IconButton, Paper, Stack } from '@mui/material';
import { MusicNote as MusicNoteIcon } from '@icons/music-note';
import { QuestionMarkCircle as QuestionMarkCircleIcon } from '@icons/question-mark-circle';
import { LightningBolt as LightningBoltIcon } from '@icons/lightning-bolt';
import { Inbox as InboxIcon } from '@icons/inbox';
import { Energy as EnergyIcon } from '@icons/energy';
// Import Swiper React components
import { Swiper, SwiperSlide, useSwiper } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';

// import required modules
import { Navigation, Pagination } from 'swiper';
import { useDispatch } from 'react-redux';
import useAppSelector from '@hooks/use-app-selector';
import { IHeadphone, IHeadphoneReducer } from 'redux/interfaces';
import { fetchHeadphonesAction } from 'redux/actions/headphone';
import { AppDispatch } from 'redux/store';

const earningCap = {
  dailyMax: 50,
  currentEarn: 22.93,
};

const energyCap = {
  max: 4,
  currentEnergy: 1,
};

// const headphones = [
//   { id: '#16452324', image: '/images/headphone_gold.png', level: 5, energy: '100%', type: 'rare' },
//   { id: '#24568454235', image: '/images/headphone_none.png', level: 1, energy: '100%', type: 'common' },
//   { id: '#3347545', image: '/images/headphone_basic.png', level: 20, energy: '100%', type: 'uncommon' },
// ];

const Home: Page = () => {
  const [val, setVal] = useState(true);
  const dispatch: AppDispatch = useDispatch();
  const { headphones } = useAppSelector<IHeadphoneReducer | null>((state) => state.headphone);
  const pending = useAppSelector<boolean>((state) => state.headphone.pending);

  useEffect(() => {
    console.log('sdfsdf');
    dispatch(fetchHeadphonesAction());
  }, [dispatch]);

  console.log(pending);

  return (
    <>
      <Head>
        <title>L2E Proto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="main">
        <Container sx={{ height: '80vh', paddingTop: '0.5rem', backgroundColor: '#121212' }}>
          <Box>
            <Swiper
              slidesPerView={1}
              spaceBetween={8}
              loop={true}
              navigation={true}
              flipEffect={{
                limitRotation: true,
              }}
              modules={[Navigation, Pagination]}
            >
              {headphones.map((v, i) => (
                <SwiperSlide style={{ backgroundColor: '#121212' }} key={i}>
                  <Stack direction="column">
                    <Box sx={{ mb: 3 }}>
                      <img src={v.image} alt="" style={{ objectFit: 'cover', minWidth: '15rem', minHeight: '15rem' }} />
                    </Box>
                    <Stack direction={'column'} alignItems="center" justifyContent={'center'} spacing={1}>
                      <Stack direction={'row'} alignItems="center" justifyContent={'center'} spacing={3}>
                        <span style={{ color: 'white', fontSize: '0.9rem' }}>{`Lv. ${v.level}`}</span>
                        <Stack direction={'row'} alignItems="center" justifyContent={'center'} spacing={1}>
                          <div
                            style={{
                              backgroundColor: 'white',
                              borderRadius: '1.5rem',
                              display: 'flex',
                              justifyContent: 'center',
                              alignItems: 'center',
                              padding: '0.3rem',
                            }}
                          >
                            <EnergyIcon style={{ color: 'black', width: '0.6rem', height: '0.6rem' }} />
                          </div>
                          <span style={{ color: 'white', fontSize: '0.9rem' }}>{v.energy}</span>
                        </Stack>
                      </Stack>
                      <div
                        style={{
                          display: 'flex',
                          justifyContent: 'center',
                          alignItems: 'center',
                          borderRadius: '1.5rem',
                          border: 'solid 1px',
                          borderColor: 'rgba(255,255,255,0.6)',
                          paddingLeft: '0.5rem',
                          paddingRight: '0.5rem',
                        }}
                      >
                        <span style={{ color: 'rgba(255,255,255,0.6)', fontSize: '0.7rem' }}>{v.id}</span>
                      </div>
                      <span style={{ color: 'rgba(255,255,255,0.9)', fontSize: '0.9rem' }}>{v.type}</span>
                    </Stack>
                  </Stack>
                </SwiperSlide>
              ))}
            </Swiper>
          </Box>
          <Stack sx={{ px: 2 }}>
            <Stack
              sx={{ display: 'flex', flexDirection: 'row', mt: 3 }}
              alignItems="center"
              justifyContent="space-between"
            >
              <Stack flexGrow={1} sx={{ mr: 1 }} spacing={1}>
                <Stack direction={'row'} justifyContent="space-between">
                  <Stack direction={'row'} alignItems="center" justifyContent={'center'} spacing={1}>
                    <img src="/images/blb-symbol.png" alt="" style={{ width: '1.2rem', height: '1.2rem' }} />
                    <span style={{ color: 'white', fontWeight: '900', fontSize: '0.8rem' }}>0.00</span>
                  </Stack>
                  <span style={{ color: 'rgba(255,255,255,0.6)', fontWeight: '900', fontSize: '0.8rem' }}>
                    100.00 LBL
                  </span>
                </Stack>
                <div
                  style={{
                    display: 'flex',
                    width: '100%',
                    minHeight: '0.6rem',
                    backgroundImage: 'linear-gradient(180deg, #121212 -42.8%, #FFFFFF 98.21%)',
                    opacity: '0.2',
                    borderRadius: '24px',
                  }}
                />
              </Stack>
              <Stack flexGrow={1} sx={{ ml: 1 }} spacing={1}>
                <Stack direction={'row'} justifyContent="space-between">
                  <Stack direction={'row'} alignItems="center" justifyContent={'center'} spacing={1}>
                    <div
                      style={{
                        backgroundColor: 'rgba(255,255,255,1)',
                        borderRadius: '1.5rem',
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                        padding: '0.1rem',
                      }}
                    >
                      <EnergyIcon style={{ color: '#121212', width: '0.9rem', height: '0.9rem' }} />
                    </div>
                    <span style={{ color: 'white', fontSize: '0.9rem' }}>100%</span>
                  </Stack>
                  <span style={{ color: 'rgba(255,255,255,0.6)', fontWeight: '900', fontSize: '0.8rem' }}>6h left</span>
                </Stack>
                <div
                  style={{
                    display: 'flex',
                    width: '100%',
                    minHeight: '0.6rem',
                    backgroundColor: 'rgba(255,255,255,1)',
                    borderRadius: '24px',
                    boxShadow: '0rem 0rem 0.4rem #fff',
                  }}
                />
              </Stack>
            </Stack>
            <Stack spacing={1} sx={{ display: 'flex', justifyContent: 'center', mt: 4 }}>
              <Box sx={{ display: 'flex', justifyContent: 'center' }}>
                <NextLink href="/playlist/sample" passHref>
                  <div
                    style={{
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                      paddingLeft: '3rem',
                      paddingRight: '3rem',
                      backgroundColor: 'white',
                      color: 'black',
                      width: '100%',
                      minHeight: '3.5rem',
                      borderRadius: '0.5rem',
                    }}
                  >
                    <span style={{ fontSize: 'large', fontWeight: '900', fontFamily: 'Gilroy-ExtraBold' }}>
                      Go To Playlist
                    </span>
                  </div>
                </NextLink>
              </Box>
            </Stack>
          </Stack>
        </Container>
      </Box>
    </>
  );
};

Home.getLayout = (page: React.ReactElement) => (
  <AuthGuard>
    <MainLayout>{page}</MainLayout>
  </AuthGuard>
);

export default Home;
